set_attack_value(AT_BAIR, AG_CATEGORY, 1);
set_attack_value(AT_BAIR, AG_SPRITE, sprite_get("bair"));
set_attack_value(AT_BAIR, AG_NUM_WINDOWS, 3);
set_attack_value(AT_BAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_BAIR, AG_LANDING_LAG, 4);
set_attack_value(AT_BAIR, AG_HURTBOX_SPRITE, sprite_get("bair_hurt"));

set_window_value(AT_BAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_BAIR, 1, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_BAIR, 1, AG_WINDOW_VSPEED, -1);
set_window_value(AT_BAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_BAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_BAIR, 1, AG_WINDOW_SFX_FRAME, 5);

set_window_value(AT_BAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 2, AG_WINDOW_LENGTH, 12);
set_window_value(AT_BAIR, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_BAIR, 2, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_BAIR, 2, AG_WINDOW_VSPEED, -3);
set_window_value(AT_BAIR, 2, AG_WINDOW_VSPEED_TYPE, 0);

set_window_value(AT_BAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 3, AG_WINDOW_LENGTH, 9);
set_window_value(AT_BAIR, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_BAIR, 3, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_BAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 4);

set_num_hitboxes(AT_BAIR, 5);

set_hitbox_value(AT_BAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_BAIR, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_X, -59);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_Y, -73);
set_hitbox_value(AT_BAIR, 1, HG_WIDTH, 25);
set_hitbox_value(AT_BAIR, 1, HG_HEIGHT, 25);
set_hitbox_value(AT_BAIR, 1, HG_PRIORITY, 9);
set_hitbox_value(AT_BAIR, 1, HG_DAMAGE, 9);
set_hitbox_value(AT_BAIR, 1, HG_ANGLE, 270);
set_hitbox_value(AT_BAIR, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_BAIR, 1, HG_KNOCKBACK_SCALING, 1.5);
set_hitbox_value(AT_BAIR, 1, HG_BASE_HITPAUSE, 20);
set_hitbox_value(AT_BAIR, 1, HG_HITPAUSE_SCALING, 2);
set_hitbox_value(AT_BAIR, 1, HG_VISUAL_EFFECT_X_OFFSET, -0);
set_hitbox_value(AT_BAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, -0);
set_hitbox_value(AT_BAIR, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_BAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_BAIR, 1, HG_ANGLE_FLIPPER, 0);

set_hitbox_value(AT_BAIR, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_BAIR, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_X, -30);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_Y, -95);
set_hitbox_value(AT_BAIR, 2, HG_WIDTH, 70);
set_hitbox_value(AT_BAIR, 2, HG_HEIGHT, 45);
set_hitbox_value(AT_BAIR, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_BAIR, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_BAIR, 2, HG_ANGLE, 170);
set_hitbox_value(AT_BAIR, 2, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_BAIR, 2, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_BAIR, 2, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_BAIR, 2, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_BAIR, 2, HG_VISUAL_EFFECT_X_OFFSET, -0);
set_hitbox_value(AT_BAIR, 2, HG_VISUAL_EFFECT_Y_OFFSET, -0);
set_hitbox_value(AT_BAIR, 2, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_BAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_BAIR, 2, HG_ANGLE_FLIPPER, 0);

set_hitbox_value(AT_BAIR, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 3, HG_WINDOW, 2);
set_hitbox_value(AT_BAIR, 3, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_BAIR, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_X, -45);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_Y, -70);
set_hitbox_value(AT_BAIR, 3, HG_WIDTH, 55);
set_hitbox_value(AT_BAIR, 3, HG_HEIGHT, 75);
set_hitbox_value(AT_BAIR, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_BAIR, 3, HG_DAMAGE, 7);
set_hitbox_value(AT_BAIR, 3, HG_ANGLE, 170);
set_hitbox_value(AT_BAIR, 3, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_BAIR, 3, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_BAIR, 3, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_BAIR, 3, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_BAIR, 3, HG_VISUAL_EFFECT_X_OFFSET, -0);
set_hitbox_value(AT_BAIR, 3, HG_VISUAL_EFFECT_Y_OFFSET, -0);
set_hitbox_value(AT_BAIR, 3, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_BAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_BAIR, 3, HG_ANGLE_FLIPPER, 0);

set_hitbox_value(AT_BAIR, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 4, HG_WINDOW, 2);
set_hitbox_value(AT_BAIR, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_BAIR, 4, HG_LIFETIME, 8);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_X, -15);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_Y, -25);
set_hitbox_value(AT_BAIR, 4, HG_WIDTH, 90);
set_hitbox_value(AT_BAIR, 4, HG_HEIGHT, 50);
set_hitbox_value(AT_BAIR, 4, HG_PRIORITY, 5);
set_hitbox_value(AT_BAIR, 4, HG_DAMAGE, 7);
set_hitbox_value(AT_BAIR, 4, HG_ANGLE, 130);
set_hitbox_value(AT_BAIR, 4, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_BAIR, 4, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_BAIR, 4, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_BAIR, 4, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_BAIR, 4, HG_VISUAL_EFFECT_X_OFFSET, -0);
set_hitbox_value(AT_BAIR, 4, HG_VISUAL_EFFECT_Y_OFFSET, -0);
set_hitbox_value(AT_BAIR, 4, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_BAIR, 4, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_BAIR, 4, HG_ANGLE_FLIPPER, 0);

set_hitbox_value(AT_BAIR, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 5, HG_WINDOW, 2);
set_hitbox_value(AT_BAIR, 5, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_BAIR, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_X, -25);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_Y, -5);
set_hitbox_value(AT_BAIR, 5, HG_WIDTH, 15);
set_hitbox_value(AT_BAIR, 5, HG_HEIGHT, 15);
set_hitbox_value(AT_BAIR, 5, HG_PRIORITY, 9);
set_hitbox_value(AT_BAIR, 5, HG_DAMAGE, 9);
set_hitbox_value(AT_BAIR, 5, HG_ANGLE, 270);
set_hitbox_value(AT_BAIR, 5, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_BAIR, 5, HG_KNOCKBACK_SCALING, 1.5);
set_hitbox_value(AT_BAIR, 5, HG_BASE_HITPAUSE, 20);
set_hitbox_value(AT_BAIR, 5, HG_HITPAUSE_SCALING, 2);
set_hitbox_value(AT_BAIR, 5, HG_VISUAL_EFFECT_X_OFFSET, -0);
set_hitbox_value(AT_BAIR, 5, HG_VISUAL_EFFECT_Y_OFFSET, -0);
set_hitbox_value(AT_BAIR, 5, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_BAIR, 5, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_BAIR, 5, HG_ANGLE_FLIPPER, 0);