set_attack_value(AT_FSTRONG, AG_SPRITE, sprite_get("fstrong"));
set_attack_value(AT_FSTRONG, AG_NUM_WINDOWS, 4);
set_attack_value(AT_FSTRONG, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_FSTRONG, AG_HURTBOX_SPRITE, sprite_get("fstrong_hurt"));

set_window_value(AT_FSTRONG, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_LENGTH, 8);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 2);

set_window_value(AT_FSTRONG, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));

set_window_value(AT_FSTRONG, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 9);

set_window_value(AT_FSTRONG, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_LENGTH, 8);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 11);

set_window_value(AT_FSTRONG, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 5, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FSTRONG, 5, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSTRONG, 5, AG_WINDOW_ANIM_FRAME_START, 16);

set_window_value(AT_FSTRONG, 6, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 6, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FSTRONG, 6, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSTRONG, 6, AG_WINDOW_ANIM_FRAME_START, 18);

set_window_value(AT_FSTRONG, 7, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 7, AG_WINDOW_LENGTH, 20);
set_window_value(AT_FSTRONG, 7, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_FSTRONG, 7, AG_WINDOW_ANIM_FRAME_START, 12);

set_num_hitboxes(AT_FSTRONG, 9);

set_hitbox_value(AT_FSTRONG, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW_CREATION_FRAME, 9);
set_hitbox_value(AT_FSTRONG, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_X, 55);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_Y, -37);
set_hitbox_value(AT_FSTRONG, 1, HG_WIDTH, 15);
set_hitbox_value(AT_FSTRONG, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_FSTRONG, 1, HG_PRIORITY, 8);
set_hitbox_value(AT_FSTRONG, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 1, HG_ANGLE, 105);
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FSTRONG, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_HITPAUSE_SCALING, 3.0);
set_hitbox_value(AT_FSTRONG, 1, HG_EXTRA_HITPAUSE, 28);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_TECHABLE, 1);

set_hitbox_value(AT_FSTRONG, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FSTRONG, 2, HG_WINDOW_CREATION_FRAME, 9);
set_hitbox_value(AT_FSTRONG, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_X, 94);
set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_Y, -41);
set_hitbox_value(AT_FSTRONG, 2, HG_WIDTH, 40);
set_hitbox_value(AT_FSTRONG, 2, HG_HEIGHT, 37);
set_hitbox_value(AT_FSTRONG, 2, HG_PRIORITY, 7);
set_hitbox_value(AT_FSTRONG, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 2, HG_ANGLE, 120);
set_hitbox_value(AT_FSTRONG, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 2, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG, 2, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_FSTRONG, 2, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_FSTRONG, 2, HG_VISUAL_EFFECT_X_OFFSET, 15);
set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 2, HG_TECHABLE, 1);

set_hitbox_value(AT_FSTRONG, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_WINDOW, 5);
set_hitbox_value(AT_FSTRONG, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_X, 55);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_Y, -37);
set_hitbox_value(AT_FSTRONG, 3, HG_WIDTH, 15);
set_hitbox_value(AT_FSTRONG, 3, HG_HEIGHT, 30);
set_hitbox_value(AT_FSTRONG, 3, HG_PRIORITY, 8);
set_hitbox_value(AT_FSTRONG, 3, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 3, HG_ANGLE, 105);
set_hitbox_value(AT_FSTRONG, 3, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_HITPAUSE_SCALING, 3.0);
set_hitbox_value(AT_FSTRONG, 3, HG_EXTRA_HITPAUSE, 28);
set_hitbox_value(AT_FSTRONG, 3, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_FSTRONG, 3, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_TECHABLE, 1);

set_hitbox_value(AT_FSTRONG, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_FSTRONG, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 4, HG_WINDOW, 5);
set_hitbox_value(AT_FSTRONG, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 4, HG_HITBOX_X, 94);
set_hitbox_value(AT_FSTRONG, 4, HG_HITBOX_Y, -41);
set_hitbox_value(AT_FSTRONG, 4, HG_WIDTH, 40);
set_hitbox_value(AT_FSTRONG, 4, HG_HEIGHT, 37);
set_hitbox_value(AT_FSTRONG, 4, HG_PRIORITY, 7);
set_hitbox_value(AT_FSTRONG, 4, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 4, HG_ANGLE, 120);
set_hitbox_value(AT_FSTRONG, 4, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 4, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 4, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG, 4, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_FSTRONG, 4, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_FSTRONG, 4, HG_VISUAL_EFFECT_X_OFFSET, 15);
set_hitbox_value(AT_FSTRONG, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 4, HG_TECHABLE, 1);

set_hitbox_value(AT_FSTRONG, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_WINDOW, 5);
set_hitbox_value(AT_FSTRONG, 5, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_X, 126);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSTRONG, 5, HG_WIDTH, 27);
set_hitbox_value(AT_FSTRONG, 5, HG_HEIGHT, 30);
set_hitbox_value(AT_FSTRONG, 5, HG_PRIORITY, 9 );
set_hitbox_value(AT_FSTRONG, 5, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 5, HG_ANGLE, 130);
set_hitbox_value(AT_FSTRONG, 5, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 5, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 5, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG, 5, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_FSTRONG, 5, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_FSTRONG, 5, HG_VISUAL_EFFECT_X_OFFSET, 15);
set_hitbox_value(AT_FSTRONG, 5, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_FSTRONG, 6, HG_PARENT_HITBOX, 6);
set_hitbox_value(AT_FSTRONG, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 6, HG_WINDOW, 6);
set_hitbox_value(AT_FSTRONG, 6, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 6, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 6, HG_HITBOX_X, 55);
set_hitbox_value(AT_FSTRONG, 6, HG_HITBOX_Y, -37);
set_hitbox_value(AT_FSTRONG, 6, HG_WIDTH, 15);
set_hitbox_value(AT_FSTRONG, 6, HG_HEIGHT, 30);
set_hitbox_value(AT_FSTRONG, 6, HG_PRIORITY, 8);
set_hitbox_value(AT_FSTRONG, 6, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 6, HG_ANGLE, 105);
set_hitbox_value(AT_FSTRONG, 6, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 6, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 6, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_FSTRONG, 6, HG_HITPAUSE_SCALING, 3.0);
set_hitbox_value(AT_FSTRONG, 6, HG_EXTRA_HITPAUSE, 28);
set_hitbox_value(AT_FSTRONG, 6, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_FSTRONG, 6, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 6, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 6, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_FSTRONG, 7, HG_PARENT_HITBOX, 7);
set_hitbox_value(AT_FSTRONG, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 7, HG_WINDOW, 6);
set_hitbox_value(AT_FSTRONG, 7, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 7, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 7, HG_HITBOX_X, 94);
set_hitbox_value(AT_FSTRONG, 7, HG_HITBOX_Y, -41);
set_hitbox_value(AT_FSTRONG, 7, HG_WIDTH, 40);
set_hitbox_value(AT_FSTRONG, 7, HG_HEIGHT, 37);
set_hitbox_value(AT_FSTRONG, 7, HG_PRIORITY, 7);
set_hitbox_value(AT_FSTRONG, 7, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 7, HG_ANGLE, 120);
set_hitbox_value(AT_FSTRONG, 7, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 7, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 7, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 7, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG, 7, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_FSTRONG, 7, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_FSTRONG, 7, HG_VISUAL_EFFECT_X_OFFSET, 15);
set_hitbox_value(AT_FSTRONG, 7, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 7, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_FSTRONG, 8, HG_PARENT_HITBOX, 8);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_WINDOW, 6);
set_hitbox_value(AT_FSTRONG, 8, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_X, 126);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSTRONG, 8, HG_WIDTH, 27);
set_hitbox_value(AT_FSTRONG, 8, HG_HEIGHT, 30);
set_hitbox_value(AT_FSTRONG, 8, HG_PRIORITY, 8 );
set_hitbox_value(AT_FSTRONG, 8, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 8, HG_ANGLE, 130);
set_hitbox_value(AT_FSTRONG, 8, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 8, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 8, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG, 8, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_FSTRONG, 8, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_FSTRONG, 8, HG_VISUAL_EFFECT_X_OFFSET, 15);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_TECHABLE, 1);

set_hitbox_value(AT_FSTRONG, 9, HG_PARENT_HITBOX, 9);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_WINDOW, 6);
set_hitbox_value(AT_FSTRONG, 9, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_LIFETIME, 3);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_X, 158);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSTRONG, 9, HG_WIDTH, 20);
set_hitbox_value(AT_FSTRONG, 9, HG_HEIGHT, 20);
set_hitbox_value(AT_FSTRONG, 9, HG_PRIORITY, 9 );
set_hitbox_value(AT_FSTRONG, 9, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 9, HG_ANGLE, 135);
set_hitbox_value(AT_FSTRONG, 9, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FSTRONG, 9, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 9, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG, 9, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_FSTRONG, 9, HG_VISUAL_EFFECT, 197);
set_hitbox_value(AT_FSTRONG, 9, HG_VISUAL_EFFECT_X_OFFSET, 15);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_TECHABLE, 1);